-- 임시테이블 삭제(존재 시)
IF OBJECT_ID('tempdb..#TempTable') IS NOT NULL
BEGIN
	DROP TABLE #TempTable;
END

IF OBJECT_ID('tempdb..#TMP_CNS_LIST') IS NOT NULL
BEGIN
	DROP TABLE #TMP_CNS_LIST;
END


-- 임시테이블 생성
CREATE TABLE #TempTable (
	STK_CD VARCHAR(6),
	CMP_NM VARCHAR(64),
	TRD_DT DATE,
	CLOSE_PRC FLOAT,
	PRE_CLOSE_PRC FLOAT,
	HIGH_PRC FLOAT,
	PRC_RTN FLOAT,
	HIGH_PRC_RTN FLOAT,
	RPT_ID VARCHAR(32),
	ANL_DT DATE,
	RPT_TXT NVARCHAR(MAX),
	RPT_TXT_LEN INT,
	BRK_NM_KOR VARCHAR(32),
	BRK_TARGET_PRC FLOAT,
	BRK_TARGET_PRC_DT DATE,
	BRK_PREV_TARGET_PRC FLOAT,
);


-- 변수선언
DECLARE @startDate DATE;
DECLARE @endDate DATE; -- 가장 최근 종가 기준일
DECLARE @thisDate DATE;
DECLARE @prevDate DATE;
DECLARE @curDate DATETIME
SET @curDate = GETDATE(); -- 종가가 존재하는 가장 최근 영업일이 아닌 실제 '오늘'임

-- 지난 2주간 하루씩 옮겨 가며 고가가 전일종가 대비 n% 이상 높은 적이 있는 종목 찾기
--SELECT TOP 1 @endDate = DT FROM WISE.DBO.TZ_DATE WHERE SVC_WK_END_YN = 1 ORDER BY DT DESC
SELECT TOP 1 @endDate = TRD_DT FROM WISE.DBO.TS_STK_DATA ORDER BY TRD_DT DESC
SET @startDate = DATEADD(DAY, -14, @endDate);
SET @thisDate = @startDate


WHILE @thisDate <= @EndDate
	BEGIN

		SELECT TOP 1 @prevDate = DT FROM WISE.DBO.TZ_DATE WHERE TRADE_YN = '1' AND DT < @thisDate ORDER BY DT DESC
	
		INSERT INTO #TempTable ( STK_CD, CMP_NM, TRD_DT, CLOSE_PRC, PRE_CLOSE_PRC, HIGH_PRC, PRC_RTN, HIGH_PRC_RTN, RPT_ID, ANL_DT, RPT_TXT, BRK_NM_KOR)
		SELECT a.STK_CD, b.CMP_NM_KOR, a.TRD_DT, a.CLOSE_PRC, a.PRE_CLOSE_PRC, a.HIGH_PRC, a.PRC_RTN, (a.HIGH_PRC - a.PRE_CLOSE_PRC)/a.PRE_CLOSE_PRC, c.RPT_ID, c.ANL_DT, e.RPT_TXT, d.BRK_NM_KOR
		FROM WISE.DBO.TS_STK_DATA a -- @thisDate의 STK_DATA
		INNER JOIN WISE.DBO.TS_STK_DATA f
		ON a.STK_CD = f.STK_CD -- @prevDate의 STK_DATA
		AND f.TRD_DT = @prevDate
		LEFT OUTER JOIN WISE.DBO.TS_STK_ADJ_FACTOR_OPEN h -- @prevDate의 수정계수
		ON a.STK_CD = h.STK_CD
		AND @prevDate BETWEEN h.START_DT and h.TRD_DT
		INNER JOIN WISE.DBO.TC_COMPANY b
		ON a.STK_CD = b.CMP_CD
		INNER JOIN WISE.DBO.TT_EST_REPORT c
		ON a.STK_CD = c.CMP_CD
		AND c.ANL_DT = CONVERT(VARCHAR(8), @curDate, 112)
		INNER JOIN WISE.DBO.TT_BROKERAGE d
		ON c.BRK_CD = d.BRK_CD
		LEFT OUTER JOIN WISE.DBO.TT_EST_REPORT_TXT e
		ON c.RPT_ID = e.RPT_ID
		WHERE a.TRD_DT = @thisDate
		AND (a.HIGH_PRC - (f.CLOSE_PRC/ISNULL(h.AADJ, 1.)))/(f.CLOSE_PRC/ISNULL(h.AADJ, 1.)) >= 0.08  -- 고가 대비 전일종가 n% 이상
		AND a.STK_CD IN ( SELECT CMP_CD FROM WISE.DBO.TT_EST_REPORT WHERE ANL_DT = CONVERT(VARCHAR(8), @curDate, 112) GROUP BY CMP_CD ) -- 오늘 리포트 발간된 종목만을 대상으로 한정

		SET @thisDate = DATEADD(DAY, 1, @thisDate)

	END


UPDATE a
SET a.BRK_TARGET_PRC = b.TARGET_PRC -- 개별 증권사 발표 개별 리포트의 목표주가
	,a.BRK_TARGET_PRC_DT = b.ANL_DT
	,a.BRK_PREV_TARGET_PRC = b.PRE_TARGET_PRC
FROM #TempTable a
LEFT OUTER JOIN WISE.DBO.TT_EST_REPORT b
ON a.RPT_ID = b.RPT_ID


SELECT CMP_CD
, RECOM_TYP_DT = @endDate
, RECOM_TYP_AVG  = MAX(CASE WHEN ITEM_CD = 761010000 THEN VAL_AVG END) --투자의견
, RECOM_TYP_MAX  = MAX(CASE WHEN ITEM_CD = 761010100 THEN VAL_AVG END) --투자의견(최고)
, RECOM_TYP_MIN  = MAX(CASE WHEN ITEM_CD = 761010200 THEN VAL_AVG END) --투자의견(최저)
, RECOM_TYP_MID  = MAX(CASE WHEN ITEM_CD = 761010300 THEN VAL_AVG END) --투자의견(중앙값)
, TARGET_PRC_AVG = MAX(CASE WHEN ITEM_CD = 761250000 THEN VAL_AVG END) --목표주가(Adj.)
, TARGET_PRC_MAX = MAX(CASE WHEN ITEM_CD = 761250100 THEN VAL_AVG END) --목표주가(Adj., 최고)
, TARGET_PRC_MIN = MAX(CASE WHEN ITEM_CD = 761250200 THEN VAL_AVG END) --목표주가(Adj., 최저)
, TARGET_PRC_MID = MAX(CASE WHEN ITEM_CD = 761250300 THEN VAL_AVG END) --목표주가(Adj., 중앙값)
, TARGET_PRC_DIFF = MAX(CASE WHEN ITEM_CD = 761036000 THEN VAL_AVG END) --목표주가괴리율
, TARGET_PRC_CHG  = MAX(CASE WHEN ITEM_CD = 761156000 THEN VAL_AVG END) --목표주가 변화율(1주)
, TARGET_PRC_DT = @endDate
, RECOM_TYP_CNT  = MAX(CASE WHEN ITEM_CD = 761010000 THEN VAL_CNT END) --투자의견 CNT
, TARGET_PRC_CNT  = MAX(CASE WHEN ITEM_CD = 761250000 THEN VAL_CNT END) --목표주가(Adj.) CNT
, TARGET_PRC_UP_1W = MAX(CASE WHEN ITEM_CD = 761031000 THEN VAL_AVG END) --목표주가상향수(1주)
, TARGET_PRC_DOWN_1W  = MAX(CASE WHEN ITEM_CD = 761032000 THEN VAL_AVG END) -- 목표주가하향수(1주)
, TARGET_PRC_HOLD_1W  = MAX(CASE WHEN ITEM_CD = 761033000 THEN VAL_AVG END) --목표주가유지수(1주)
, TARGET_PRC_NEW_1W  = MAX(CASE WHEN ITEM_CD = 761034000 THEN VAL_AVG END) --신규목표주가수(1주)
, TARGET_PRC_UP_DOWN_1W = MAX(CASE WHEN ITEM_CD = 761066000 THEN VAL_AVG END) -- 목표주가상향-목표주가하향(1주)
INTO #TMP_CNS_LIST
FROM WISE.dbo.TT_CMP_CNS_EXT_DATA3
WHERE CNS_DT = @endDate AND ITEM_CD IN ('761010000','761010100','761010200','761010300','761250000','761250100','761250200','761250300','761036000','761156000', '761050000','761056000','761031000','761032000','761033000','761034000','761066000')
AND TERM_TYP = 1
GROUP BY CMP_CD 

--SELECT TOP 10 * FROM WISE.DBO.TT_CMP_CNS_EXT_DATA3 ORDER BY CNS_DT DESC

--SELECT *
--FROM WISE.DBO.TT_CMP_CNS_EXT_DATA3
--WHERE CMP_CD = '006280'
--AND ITEM_CD = '761250000'
--AND TERM_TYP = 1
--AND CNS_DT > '2023-01-01'
--ORDER BY CNS_DT DESC


DECLARE @threeMonthsBefore DATE;
SELECT TOP 1 @threeMonthsBefore = DT FROM WISE.DBO.TZ_DATE WHERE TRADE_YN = '1' AND DT <= DATEADD(month, -3, @endDate) ORDER BY DT DESC
--SELECT @threeMonthsBefore


SELECT a.* 
, c.RECOM_TYP_DT
, c.RECOM_TYP_AVG
, c.RECOM_TYP_MAX  
, c.RECOM_TYP_MIN  
, c.RECOM_TYP_MID  
, c.TARGET_PRC_AVG 
, d.VAL_AVG AS 'TARGET_PRC_AVG_3_MONTHS_BEFORE'
, c.TARGET_PRC_MAX 
, c.TARGET_PRC_MIN 
, c.TARGET_PRC_MID 
, c.TARGET_PRC_DIFF
, c.TARGET_PRC_CHG 
, c.TARGET_PRC_DT 
, c.RECOM_TYP_CNT 
, c.TARGET_PRC_CNT
, c.TARGET_PRC_UP_1W
, c.TARGET_PRC_DOWN_1W
, c.TARGET_PRC_HOLD_1W
, c.TARGET_PRC_NEW_1W 
, c.TARGET_PRC_UP_DOWN_1W
FROM #TempTable a
	LEFT OUTER JOIN #TMP_CNS_LIST c
		ON a.STK_CD = c.CMP_CD 
	LEFT OUTER JOIN WISE.DBO.TT_CMP_CNS_EXT_DATA3 d
		on a.STK_CD = d.CMP_CD
		AND d.ITEM_CD = '761250000'--목표주가(adj)
		AND d.CNS_DT = @threeMonthsBefore






